apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.serviceAccountName }}-role
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccountName }}-binding
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.serviceAccountName }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}