apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-sidecar-helper
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-sidecar-helper-role
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-sidecar-helper
{{ if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
{{ end }}
roleRef:
  kind: Role
  name: envoy-sidecar-helper-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: envoy-sidecar-helper
  namespace: {{ .Release.Namespace }}